
// Master curriculum registry: 30 unique topics per language/tool
// Topics progress from beginner → intermediate → advanced

export const curriculum: { [language: string]: string[] } = {
  c: [
    'Introduction to C',
    'Structure of a C Program',
    'Variables',
    'Data Types',
    'Constants and Literals',
    'Input and Output',
    'Arithmetic Operators',
    'Relational and Logical Operators',
    'Type Casting',
    'If Statement',
    'If-Else Statement',
    'Switch Statement',
    'For Loop',
    'While Loop',
    'Do-While Loop',
    'Break and Continue',
    'Functions Basics',
    'Function Arguments and Return',
    'Recursion',
    'One-Dimensional Arrays',
    'Two-Dimensional Arrays',
    'String Basics',
    'Pointers Introduction',
    'Pointer Arithmetic',
    'Dynamic Memory Allocation',
    'Structures',
    'File Handling Basics',
    'Preprocessor Directives',
    'Linked List Basics',
    'C Mastery Final Challenge',
  ],
  'c++': [
    'Introduction to C++',
    'C++ Program Structure',
    'Variables and Constants',
    'Data Types in C++',
    'Input and Output Streams',
    'Operators',
    'If and If-Else',
    'Switch Statement',
    'For Loop',
    'While and Do-While',
    'Functions',
    'Function Overloading',
    'Arrays',
    'Strings in C++',
    'Pointers',
    'References',
    'Dynamic Memory (new/delete)',
    'Classes and Objects',
    'Constructors',
    'Inheritance Basics',
    'Polymorphism',
    'Virtual Functions',
    'Exception Handling',
    'Templates Basics',
    'Vectors',
    'Maps and Sets',
    'Iterators',
    'Lambda Expressions',
    'Smart Pointers',
    'C++ Mastery Final Challenge',
  ],
  java: [
    'Introduction to Java',
    'Java Program Structure',
    'Variables and Data Types',
    'Operators in Java',
    'String Basics',
    'Input with Scanner',
    'If and If-Else',
    'Switch Statement',
    'For Loop',
    'While and Do-While',
    'Arrays',
    'Methods',
    'Method Overloading',
    'Recursion',
    'Classes and Objects',
    'Constructors',
    'Inheritance',
    'Polymorphism',
    'Abstract Classes',
    'Interfaces',
    'Exception Handling',
    'ArrayList',
    'HashMap',
    'Generics Basics',
    'File Handling',
    'Lambda Expressions',
    'Stream API Basics',
    'Multithreading Basics',
    'Collections Framework',
    'Java Mastery Final Challenge',
  ],
  python: [
    'Introduction to Python',
    'Variables and Assignment',
    'Data Types',
    'Strings',
    'Input and Output',
    'Operators',
    'If Statement',
    'If-Elif-Else',
    'For Loop',
    'While Loop',
    'Functions',
    'Parameters and Arguments',
    'Return Values',
    'Lists',
    'List Comprehensions',
    'Tuples',
    'Dictionaries',
    'Sets',
    'Error Handling',
    'File Reading and Writing',
    'Modules and Import',
    'Classes and Objects',
    'Inheritance',
    'Polymorphism',
    'Decorators',
    'Generators',
    'Lambda Functions',
    'Regular Expressions',
    'JSON Handling',
    'Python Mastery Final Challenge',
  ],
  html: [
    'Introduction to HTML',
    'HTML Document Structure',
    'Headings',
    'Paragraphs and Text',
    'Links (Anchor Tag)',
    'Images',
    'Lists (Ordered and Unordered)',
    'Div and Span',
    'HTML Attributes',
    'Tables Basics',
    'Forms Introduction',
    'Text Input Fields',
    'Radio Buttons and Checkboxes',
    'Select Dropdown',
    'Form Validation',
    'Semantic HTML',
    'Header and Footer',
    'Nav Element',
    'Audio and Video',
    'Iframe',
    'Meta Tags',
    'HTML5 New Elements',
    'Data Attributes',
    'Responsive Images',
    'Canvas Basics',
    'SVG Basics',
    'Accessibility (ARIA)',
    'SEO Best Practices',
    'Web Components Basics',
    'HTML Mastery Final Challenge',
  ],
  css: [
    'Introduction to CSS',
    'CSS Selectors',
    'Colors and Backgrounds',
    'Text Styling',
    'Box Model',
    'Padding and Margin',
    'Borders and Outlines',
    'Display Property',
    'Position Property',
    'Float and Clear',
    'Flexbox Basics',
    'Flexbox Alignment',
    'CSS Grid Basics',
    'Grid Layout',
    'Responsive Design',
    'Media Queries',
    'Pseudo-Classes',
    'Pseudo-Elements',
    'Transitions',
    'Animations',
    'Transforms',
    'CSS Variables',
    'Gradients',
    'Shadows',
    'Filters',
    'Typography',
    'Units and Values',
    'Specificity',
    'CSS Architecture',
    'CSS Mastery Final Challenge',
  ],
  javascript: [
    'Introduction to JavaScript',
    'Variables (let, const, var)',
    'Data Types',
    'Operators',
    'Strings and Template Literals',
    'If-Else Statements',
    'Switch Statement',
    'For Loop',
    'While and Do-While',
    'Functions',
    'Arrow Functions',
    'Arrays',
    'Array Methods',
    'Objects',
    'Object Methods',
    'DOM Selection',
    'DOM Manipulation',
    'Events',
    'Callbacks',
    'Promises',
    'Async/Await',
    'Error Handling',
    'Classes',
    'Modules',
    'Destructuring',
    'Spread and Rest',
    'Map and Set',
    'Regular Expressions',
    'Fetch API',
    'JavaScript Mastery Final Challenge',
  ],
  sql: [
    'What is SQL + Databases',
    'SELECT Statement',
    'WHERE Clause',
    'ORDER BY',
    'DISTINCT',
    'LIMIT',
    'Comparison Operators (=, <, >)',
    'Logical Operators (AND, OR, NOT)',
    'BETWEEN',
    'IN Operator',
    'LIKE + Wildcards',
    'Aggregate Functions (COUNT, SUM)',
    'GROUP BY',
    'HAVING',
    'MIN & MAX',
    'INSERT INTO',
    'UPDATE Statement',
    'DELETE Statement',
    'CREATE TABLE',
    'Data Types (INT, VARCHAR)',
    'PRIMARY KEY',
    'FOREIGN KEY',
    'INNER JOIN',
    'LEFT JOIN',
    'RIGHT JOIN',
    'Subqueries',
    'Nested Queries',
    'Indexes (Concept)',
    'Constraints',
    'Real-World Query Challenge',
  ],
  git: [
    'What is Git + Why Version Control',
    'git init',
    'git status',
    'git add',
    'git commit',
    'Commit Messages Best Practices',
    'git log',
    'git diff',
    'git branch',
    'git checkout',
    'Branching Concept',
    'git merge',
    'Merge Conflicts',
    'git reset',
    'git revert',
    'git stash',
    'Remote Repositories',
    'git remote add',
    'git push',
    'git pull',
    'git clone',
    'What is GitHub',
    'Repositories & Commits on GitHub',
    'Forking',
    'Pull Requests',
    'Collaboration Workflow',
    '.gitignore',
    'Tags & Releases',
    'Common Git Mistakes',
    'Practical Git Scenario Challenge',
  ],
  linux: [
    'What is Linux + Terminal Basics',
    'pwd',
    'ls',
    'cd',
    'Absolute vs Relative Paths',
    'mkdir',
    'rm',
    'rmdir',
    'touch',
    'cp',
    'mv',
    'File Permissions (Concept)',
    'chmod',
    'cat',
    'nano / vi Basics',
    'head & tail',
    'grep',
    'Pipes (|)',
    'Redirection (>, >>)',
    'find',
    'man (Manual Pages)',
    'Process Basics',
    'ps',
    'kill',
    'Environment Variables',
    'echo',
    'Clear & History',
    'Package Managers (Concept)',
    'Useful Productivity Commands',
    'Real-World CLI Challenge',
  ],
  dsa: [
    'What are Data Structures',
    'What are Algorithms',
    'Time Complexity Basics',
    'Space Complexity',
    'Big O Notation',
    'Arrays (DS Perspective)',
    'Searching: Linear Search',
    'Searching: Binary Search',
    'Sorting: Bubble Sort',
    'Sorting: Selection Sort',
    'Sorting: Insertion Sort',
    'Stacks',
    'Queues',
    'Linked Lists',
    'Doubly Linked Lists',
    'Hash Tables',
    'Recursion in DSA',
    'Trees Introduction',
    'Binary Trees',
    'Binary Search Trees',
    'Tree Traversals',
    'Heaps',
    'Graphs Introduction',
    'Graph Representations',
    'BFS (Breadth-First Search)',
    'DFS (Depth-First Search)',
    'Sorting: Merge Sort',
    'Sorting: Quick Sort',
    'Dynamic Programming Basics',
    'DSA Mastery Final Challenge',
  ],
  'rest-apis': [
    'What are APIs',
    'What is REST',
    'HTTP Methods (GET, POST)',
    'HTTP Status Codes',
    'URL Structure & Endpoints',
    'Request Headers',
    'Request Body',
    'Response Body',
    'Query Parameters',
    'Path Parameters',
    'JSON in APIs',
    'Authentication Basics',
    'API Keys',
    'Bearer Tokens',
    'CRUD Operations via API',
    'GET Requests in Detail',
    'POST Requests in Detail',
    'PUT vs PATCH',
    'DELETE Requests',
    'Error Handling in APIs',
    'Rate Limiting',
    'Pagination',
    'Versioning',
    'CORS Basics',
    'API Testing with Tools',
    'Webhooks',
    'RESTful Design Principles',
    'API Documentation',
    'Common API Patterns',
    'Real-World API Challenge',
  ],
  json: [
    'What is JSON',
    'JSON Syntax Rules',
    'JSON Data Types',
    'JSON Objects',
    'JSON Arrays',
    'Nested JSON',
    'JSON vs XML',
    'Parsing JSON (Concept)',
    'Stringify JSON',
    'JSON in APIs',
    'JSON Schema Basics',
    'Accessing JSON Values',
    'Modifying JSON',
    'JSON with JavaScript',
    'JSON with Python',
    'JSON Files',
    'Reading JSON Files',
    'Writing JSON Files',
    'JSON Validation',
    'Pretty Printing JSON',
    'JSON Path Basics',
    'Complex Nested Structures',
    'Arrays of Objects',
    'JSON Best Practices',
    'Common JSON Errors',
    'JSON and Databases',
    'JSON Web Tokens (JWT)',
    'JSON Configuration Files',
    'JSON Transformation',
    'JSON Mastery Challenge',
  ],
  debugging: [
    'What is Debugging',
    'Types of Errors',
    'Syntax Errors',
    'Runtime Errors',
    'Logic Errors',
    'Reading Error Messages',
    'Print Debugging',
    'Using Breakpoints',
    'Step-by-Step Execution',
    'Watch Variables',
    'Call Stack',
    'Common Off-by-One Errors',
    'Null/Undefined Errors',
    'Type Errors',
    'Index Out of Bounds',
    'Infinite Loops',
    'Debugging Conditionals',
    'Debugging Functions',
    'Debugging Loops',
    'Debugging Recursion',
    'Browser DevTools Basics',
    'Console Methods',
    'Network Debugging',
    'Error Handling Patterns',
    'Try-Catch Strategies',
    'Logging Best Practices',
    'Rubber Duck Debugging',
    'Code Review for Bugs',
    'Debugging Mindset',
    'Debugging Mastery Challenge',
  ],
  regex: [
    'What are Regular Expressions',
    'Literal Characters',
    'The Dot (.) Metacharacter',
    'Character Classes []',
    'Negated Character Classes [^]',
    'Predefined Classes (\\d, \\w, \\s)',
    'Quantifiers (* + ?)',
    'Exact Quantifiers {n}',
    'Range Quantifiers {n,m}',
    'Anchors (^ and $)',
    'Word Boundaries (\\b)',
    'Alternation (|)',
    'Grouping with ()',
    'Capturing Groups',
    'Non-Capturing Groups',
    'Backreferences',
    'Greedy vs Lazy Matching',
    'Lookahead (?=)',
    'Negative Lookahead (?!)',
    'Lookbehind (?<=)',
    'Escape Characters',
    'Matching Emails',
    'Matching Phone Numbers',
    'Matching URLs',
    'Search and Replace',
    'Flags (g, i, m)',
    'Regex in JavaScript',
    'Regex in Python',
    'Common Regex Patterns',
    'Regex Mastery Challenge',
  ],
};

// Tools/technologies track identifiers (keys in curriculum that are tools, not languages)
export const toolTracks = ['sql', 'git', 'linux', 'dsa', 'rest-apis', 'json', 'debugging', 'regex'];
export const languageTracks = ['c', 'c++', 'java', 'python', 'html', 'css', 'javascript'];

export const getTopic = (language: string, level: number): string => {
  const lang = language.toLowerCase();
  const topics = curriculum[lang];
  if (!topics || level < 1 || level > topics.length) {
    return `${language} Topic ${level}`;
  }
  return topics[level - 1];
};

export const getDifficulty = (level: number): string => {
  if (level <= 10) return 'Beginner';
  if (level <= 20) return 'Intermediate';
  return 'Advanced';
};
