
// Master curriculum registry: 30 unique topics per language
// Topics progress from beginner → intermediate → advanced

export const curriculum: { [language: string]: string[] } = {
  c: [
    'Introduction to C',
    'Structure of a C Program',
    'Variables',
    'Data Types',
    'Constants and Literals',
    'Input and Output',
    'Arithmetic Operators',
    'Relational and Logical Operators',
    'Type Casting',
    'If Statement',
    'If-Else Statement',
    'Switch Statement',
    'For Loop',
    'While Loop',
    'Do-While Loop',
    'Break and Continue',
    'Functions Basics',
    'Function Arguments and Return',
    'Recursion',
    'One-Dimensional Arrays',
    'Two-Dimensional Arrays',
    'String Basics',
    'Pointers Introduction',
    'Pointer Arithmetic',
    'Dynamic Memory Allocation',
    'Structures',
    'File Handling Basics',
    'Preprocessor Directives',
    'Linked List Basics',
    'C Mastery Final Challenge',
  ],
  'c++': [
    'Introduction to C++',
    'C++ Program Structure',
    'Variables and Constants',
    'Data Types in C++',
    'Input and Output Streams',
    'Operators',
    'If and If-Else',
    'Switch Statement',
    'For Loop',
    'While and Do-While',
    'Functions',
    'Function Overloading',
    'Arrays',
    'Strings in C++',
    'Pointers',
    'References',
    'Dynamic Memory (new/delete)',
    'Classes and Objects',
    'Constructors',
    'Inheritance Basics',
    'Polymorphism',
    'Virtual Functions',
    'Exception Handling',
    'Templates Basics',
    'Vectors',
    'Maps and Sets',
    'Iterators',
    'Lambda Expressions',
    'Smart Pointers',
    'C++ Mastery Final Challenge',
  ],
  java: [
    'Introduction to Java',
    'Java Program Structure',
    'Variables and Data Types',
    'Operators in Java',
    'String Basics',
    'Input with Scanner',
    'If and If-Else',
    'Switch Statement',
    'For Loop',
    'While and Do-While',
    'Arrays',
    'Methods',
    'Method Overloading',
    'Recursion',
    'Classes and Objects',
    'Constructors',
    'Inheritance',
    'Polymorphism',
    'Abstract Classes',
    'Interfaces',
    'Exception Handling',
    'ArrayList',
    'HashMap',
    'Generics Basics',
    'File Handling',
    'Lambda Expressions',
    'Stream API Basics',
    'Multithreading Basics',
    'Collections Framework',
    'Java Mastery Final Challenge',
  ],
  python: [
    'Introduction to Python',
    'Variables and Assignment',
    'Data Types',
    'Strings',
    'Input and Output',
    'Operators',
    'If Statement',
    'If-Elif-Else',
    'For Loop',
    'While Loop',
    'Functions',
    'Parameters and Arguments',
    'Return Values',
    'Lists',
    'List Comprehensions',
    'Tuples',
    'Dictionaries',
    'Sets',
    'Error Handling',
    'File Reading and Writing',
    'Modules and Import',
    'Classes and Objects',
    'Inheritance',
    'Polymorphism',
    'Decorators',
    'Generators',
    'Lambda Functions',
    'Regular Expressions',
    'JSON Handling',
    'Python Mastery Final Challenge',
  ],
  html: [
    'Introduction to HTML',
    'HTML Document Structure',
    'Headings',
    'Paragraphs and Text',
    'Links (Anchor Tag)',
    'Images',
    'Lists (Ordered and Unordered)',
    'Div and Span',
    'HTML Attributes',
    'Tables Basics',
    'Forms Introduction',
    'Text Input Fields',
    'Radio Buttons and Checkboxes',
    'Select Dropdown',
    'Form Validation',
    'Semantic HTML',
    'Header and Footer',
    'Nav Element',
    'Audio and Video',
    'Iframe',
    'Meta Tags',
    'HTML5 New Elements',
    'Data Attributes',
    'Responsive Images',
    'Canvas Basics',
    'SVG Basics',
    'Accessibility (ARIA)',
    'SEO Best Practices',
    'Web Components Basics',
    'HTML Mastery Final Challenge',
  ],
  css: [
    'Introduction to CSS',
    'CSS Selectors',
    'Colors and Backgrounds',
    'Text Styling',
    'Box Model',
    'Padding and Margin',
    'Borders and Outlines',
    'Display Property',
    'Position Property',
    'Float and Clear',
    'Flexbox Basics',
    'Flexbox Alignment',
    'CSS Grid Basics',
    'Grid Layout',
    'Responsive Design',
    'Media Queries',
    'Pseudo-Classes',
    'Pseudo-Elements',
    'Transitions',
    'Animations',
    'Transforms',
    'CSS Variables',
    'Gradients',
    'Shadows',
    'Filters',
    'Typography',
    'Units and Values',
    'Specificity',
    'CSS Architecture',
    'CSS Mastery Final Challenge',
  ],
  javascript: [
    'Introduction to JavaScript',
    'Variables (let, const, var)',
    'Data Types',
    'Operators',
    'Strings and Template Literals',
    'If-Else Statements',
    'Switch Statement',
    'For Loop',
    'While and Do-While',
    'Functions',
    'Arrow Functions',
    'Arrays',
    'Array Methods',
    'Objects',
    'Object Methods',
    'DOM Selection',
    'DOM Manipulation',
    'Events',
    'Callbacks',
    'Promises',
    'Async/Await',
    'Error Handling',
    'Classes',
    'Modules',
    'Destructuring',
    'Spread and Rest',
    'Map and Set',
    'Regular Expressions',
    'Fetch API',
    'JavaScript Mastery Final Challenge',
  ],
};

export const getTopic = (language: string, level: number): string => {
  const lang = language.toLowerCase();
  const topics = curriculum[lang];
  if (!topics || level < 1 || level > topics.length) {
    return `${language} Topic ${level}`;
  }
  return topics[level - 1];
};

export const getDifficulty = (level: number): string => {
  if (level <= 10) return 'Beginner';
  if (level <= 20) return 'Intermediate';
  return 'Advanced';
};
