
// Master curriculum registry: 100 unique topics per language
// Topics progress from beginner → intermediate → advanced

export const curriculum: { [language: string]: string[] } = {
  c: [
    // Beginner Foundations (1-20)
    'Introduction to C',
    'Structure of a C Program',
    'Variables',
    'Data Types',
    'Constants and Literals',
    'Input and Output',
    'Arithmetic Operators',
    'Relational and Logical Operators',
    'Type Casting',
    'If Statement',
    'If-Else Statement',
    'Nested If Statements',
    'Switch Statement',
    'For Loop',
    'While Loop',
    'Do-While Loop',
    'Break and Continue',
    'Basic Programs',
    'Functions Basics',
    'Function Arguments and Return',
    // Core Programming (21-40)
    'Scope and Lifetime',
    'Storage Classes',
    'Recursion',
    'One-Dimensional Arrays',
    'Two-Dimensional Arrays',
    'Multi-Dimensional Arrays',
    'String Basics',
    'String Functions',
    'Character Handling',
    'Pointers Introduction',
    'Pointer Arithmetic',
    'Pointers and Arrays',
    'Pointers and Functions',
    'Call by Value vs Reference',
    'Dynamic Memory Allocation',
    'Structures',
    'Nested Structures',
    'Unions',
    'Typedef',
    'Enumerations',
    // Intermediate (41-70)
    'File Handling Basics',
    'File Modes',
    'Binary File Operations',
    'Command Line Arguments',
    'Preprocessor Directives',
    'Macros',
    'Header Files',
    'Bitwise Operators',
    'Error Handling in C',
    'Linked List Basics',
    'Stack Implementation',
    'Queue Implementation',
    'Linear Search',
    'Binary Search',
    'Bubble Sort',
    'Selection Sort',
    'Insertion Sort',
    'Function Pointers',
    'Advanced Pointer Usage',
    'Memory Layout',
    'Const and Volatile',
    'Modular Programming',
    'Debugging Techniques',
    'String Manipulation Algorithms',
    'Array Manipulation Algorithms',
    'Matrix Operations',
    'Circular Linked List',
    'Doubly Linked List',
    'Hash Tables',
    'Priority Queues',
    // Advanced (71-100)
    'Tree Basics',
    'Binary Search Trees',
    'Tree Traversal',
    'Graph Basics',
    'Graph Traversal (BFS/DFS)',
    'Merge Sort',
    'Quick Sort',
    'Heap Sort',
    'Memory Optimization',
    'Advanced Recursion',
    'Complex File Systems',
    'Advanced Macros',
    'System-Level Concepts',
    'Bit Manipulation',
    'Advanced Structs and Unions',
    'Network Programming Basics',
    'Process Control',
    'Signal Handling',
    'Multithreading Basics',
    'Static and Dynamic Libraries',
    'Makefiles',
    'Code Optimization',
    'Design Patterns in C',
    'Embedded C Basics',
    'Advanced Data Structures',
    'Algorithm Complexity',
    'Real-World C Project: Calculator',
    'Real-World C Project: File Manager',
    'Real-World C Project: Data Processor',
    'C Mastery Final Challenge',
  ],
  'c++': [
    // Basics (1-20)
    'Introduction to C++',
    'C++ Program Structure',
    'Variables and Constants',
    'Data Types in C++',
    'Input and Output Streams',
    'Operators',
    'Type Conversion',
    'If and If-Else',
    'Switch Statement',
    'For Loop',
    'While and Do-While',
    'Break, Continue, Goto',
    'Functions',
    'Default and Inline Functions',
    'Function Overloading',
    'Arrays',
    'Strings in C++',
    'Pointers',
    'References',
    'Dynamic Memory (new/delete)',
    // OOP Core (21-45)
    'Classes and Objects',
    'Access Specifiers',
    'Constructors',
    'Destructors',
    'Copy Constructor',
    'This Pointer',
    'Static Members',
    'Friend Functions',
    'Operator Overloading',
    'Encapsulation',
    'Inheritance Basics',
    'Types of Inheritance',
    'Method Overriding',
    'Virtual Functions',
    'Abstract Classes',
    'Polymorphism',
    'Interfaces',
    'Namespaces',
    'Exception Handling',
    'Try-Catch-Throw',
    'File Handling in C++',
    'String Streams',
    'Typecasting in C++',
    'Preprocessor in C++',
    'Enumerations and Typedef',
    // STL & Templates (46-70)
    'Templates Basics',
    'Function Templates',
    'Class Templates',
    'STL Introduction',
    'Vectors',
    'Lists and Deques',
    'Stacks and Queues (STL)',
    'Sets and Multisets',
    'Maps and Multimaps',
    'Iterators',
    'Algorithms (STL)',
    'Pairs and Tuples',
    'Lambda Expressions',
    'Smart Pointers (unique_ptr)',
    'Smart Pointers (shared_ptr)',
    'Move Semantics',
    'Rvalue References',
    'Type Traits',
    'RAII Pattern',
    'Custom Iterators',
    'Functors',
    'Regex in C++',
    'Chrono Library',
    'Random Number Generation',
    'Concurrency Basics',
    // Advanced (76-100)
    'Threads and Mutexes',
    'Condition Variables',
    'Async and Futures',
    'Advanced Templates',
    'Template Metaprogramming',
    'Variadic Templates',
    'SFINAE',
    'Concepts (C++20)',
    'Ranges (C++20)',
    'Modules (C++20)',
    'Coroutines',
    'Design Patterns: Singleton',
    'Design Patterns: Factory',
    'Design Patterns: Observer',
    'Memory Pool Allocation',
    'Custom Allocators',
    'Binary File I/O',
    'Network Programming',
    'Unit Testing',
    'Build Systems (CMake)',
    'Code Profiling',
    'Advanced OOP Design',
    'Competitive Programming Basics',
    'Advanced Algorithms',
    'C++ Mastery Final Challenge',
  ],
  java: [
    // Basics (1-20)
    'Introduction to Java',
    'Java Program Structure',
    'Variables and Data Types',
    'Operators in Java',
    'Type Casting',
    'String Basics',
    'Input with Scanner',
    'If and If-Else',
    'Switch Statement',
    'For Loop',
    'While and Do-While',
    'Break and Continue',
    'Arrays',
    'Multi-Dimensional Arrays',
    'Methods',
    'Method Overloading',
    'Recursion',
    'Math Class',
    'Wrapper Classes',
    'Basic String Methods',
    // OOP Core (21-45)
    'Classes and Objects',
    'Constructors',
    'This Keyword',
    'Access Modifiers',
    'Getters and Setters',
    'Static Keyword',
    'Final Keyword',
    'Encapsulation',
    'Inheritance',
    'Method Overriding',
    'Super Keyword',
    'Polymorphism',
    'Abstract Classes',
    'Interfaces',
    'Multiple Inheritance via Interfaces',
    'Packages',
    'Inner Classes',
    'Anonymous Classes',
    'Enums',
    'Object Class Methods',
    'Comparable and Comparator',
    'Generics Basics',
    'Bounded Types',
    'Wildcards',
    'Type Erasure',
    // Collections & APIs (46-70)
    'Collections Framework Overview',
    'ArrayList',
    'LinkedList',
    'Stack and Queue',
    'HashSet and TreeSet',
    'HashMap and TreeMap',
    'Iterators',
    'Exception Handling',
    'Try-Catch-Finally',
    'Custom Exceptions',
    'File Handling (FileReader/Writer)',
    'BufferedReader and Writer',
    'Serialization',
    'StringBuilder and StringBuffer',
    'Regular Expressions',
    'Date and Time API',
    'Lambda Expressions',
    'Functional Interfaces',
    'Stream API Basics',
    'Stream Operations',
    'Optional Class',
    'Annotations',
    'Reflection',
    'JUnit Testing Basics',
    'Assertions',
    // Advanced (76-100)
    'Multithreading Basics',
    'Thread Synchronization',
    'Executors Framework',
    'Concurrent Collections',
    'CompletableFuture',
    'Socket Programming',
    'HTTP Client',
    'JDBC Basics',
    'PreparedStatement',
    'Design Patterns: Singleton',
    'Design Patterns: Factory',
    'Design Patterns: Observer',
    'Design Patterns: Strategy',
    'JVM Architecture',
    'Garbage Collection',
    'Memory Management',
    'ClassLoaders',
    'Modules (Java 9+)',
    'Records and Sealed Classes',
    'Pattern Matching',
    'Advanced Streams',
    'Reactive Programming Basics',
    'Build Tools (Maven/Gradle)',
    'Java Best Practices',
    'Java Mastery Final Challenge',
  ],
  python: [
    // Basics (1-20)
    'Introduction to Python',
    'Variables and Assignment',
    'Data Types',
    'Numbers and Math',
    'Strings',
    'String Methods',
    'Input and Output',
    'Operators',
    'Boolean and Comparisons',
    'If Statement',
    'If-Elif-Else',
    'For Loop',
    'While Loop',
    'Break, Continue, Pass',
    'Range Function',
    'Functions',
    'Parameters and Arguments',
    'Return Values',
    'Scope and Namespaces',
    'Basic Built-in Functions',
    // Core Structures (21-45)
    'Lists',
    'List Methods',
    'List Comprehensions',
    'Tuples',
    'Sets',
    'Dictionaries',
    'Dictionary Methods',
    'Dictionary Comprehensions',
    'Nested Data Structures',
    'String Formatting',
    'Unpacking and Packing',
    'Lambda Functions',
    'Map, Filter, Reduce',
    'Sorting',
    'Modules and Import',
    'Creating Modules',
    'Packages',
    'PIP and Libraries',
    'Virtual Environments',
    'Error Handling Basics',
    'Try-Except-Finally',
    'Custom Exceptions',
    'Assertions',
    'Logging',
    'Debugging Techniques',
    // OOP & Intermediate (46-70)
    'Classes and Objects',
    'Constructor (__init__)',
    'Instance and Class Variables',
    'Methods',
    'Inheritance',
    'Multiple Inheritance',
    'Method Resolution Order',
    'Polymorphism',
    'Encapsulation',
    'Properties and Decorators',
    'Magic Methods',
    'Operator Overloading',
    'Iterators',
    'Generators',
    'File Reading',
    'File Writing',
    'CSV Files',
    'JSON Handling',
    'Regular Expressions',
    'OS Module',
    'Datetime Module',
    'Collections Module',
    'Functools Module',
    'Type Hints',
    'Unit Testing (unittest)',
    // Advanced (76-100)
    'Decorators',
    'Class Decorators',
    'Context Managers',
    'With Statement',
    'Closures',
    'Recursion Patterns',
    'Data Classes',
    'Abstract Base Classes',
    'Metaclasses',
    'Descriptors',
    'Slots',
    'Weak References',
    'Multithreading',
    'Multiprocessing',
    'Async/Await',
    'Asyncio',
    'Sockets',
    'Database Access (sqlite3)',
    'Web Scraping Basics',
    'API Requests',
    'Pathlib',
    'Argparse',
    'Advanced Comprehensions',
    'Performance Optimization',
    'Python Mastery Final Challenge',
  ],
  html: [
    // Foundations (1-20)
    'Introduction to HTML',
    'HTML Document Structure',
    'Headings',
    'Paragraphs and Text',
    'Line Breaks and Horizontal Rules',
    'Bold, Italic, Underline',
    'Links (Anchor Tag)',
    'Images',
    'Lists (Ordered and Unordered)',
    'Nested Lists',
    'HTML Comments',
    'Special Characters and Entities',
    'Div and Span',
    'Block vs Inline Elements',
    'HTML Attributes',
    'Id and Class Attributes',
    'Tables Basics',
    'Table Rows and Columns',
    'Table Spanning',
    'Forms Introduction',
    // Structure & Forms (21-45)
    'Text Input Fields',
    'Password and Email Fields',
    'Radio Buttons',
    'Checkboxes',
    'Select Dropdown',
    'Textarea',
    'Form Buttons',
    'Form Action and Method',
    'Form Validation Attributes',
    'Input Types (number, date, etc)',
    'Fieldset and Legend',
    'Label Element',
    'Datalist',
    'Semantic HTML Introduction',
    'Header and Footer',
    'Nav Element',
    'Main and Section',
    'Article and Aside',
    'Figure and Figcaption',
    'Audio Element',
    'Video Element',
    'Iframe',
    'Embed and Object',
    'Meta Tags',
    'Viewport Meta Tag',
    // Advanced Markup (46-70)
    'HTML5 New Elements',
    'Data Attributes',
    'Microdata',
    'Open Graph Tags',
    'Favicon',
    'Link Element',
    'Style Element',
    'Script Element',
    'Noscript',
    'Template Element',
    'Picture and Source',
    'Responsive Images (srcset)',
    'Details and Summary',
    'Progress and Meter',
    'Dialog Element',
    'Canvas Basics',
    'SVG Basics',
    'SVG Shapes',
    'SVG Paths',
    'Accessibility Basics (ARIA)',
    'ARIA Roles',
    'ARIA Properties',
    'Keyboard Navigation',
    'HTML Forms Advanced',
    'Custom Data Validation',
    // Expert (76-100)
    'SEO Best Practices',
    'Structured Data (JSON-LD)',
    'Performance: Lazy Loading',
    'Performance: Preload/Prefetch',
    'Web Components Basics',
    'Custom Elements',
    'Shadow DOM',
    'HTML Templates',
    'Content Security Policy',
    'Cross-Origin Resource Sharing',
    'Web Storage (localStorage)',
    'Session Storage',
    'IndexedDB Basics',
    'Drag and Drop API',
    'Geolocation API',
    'Notification API',
    'Clipboard API',
    'History API',
    'Intersection Observer',
    'Mutation Observer',
    'Service Workers Intro',
    'Progressive Web App Basics',
    'HTML Email Basics',
    'HTML Best Practices',
    'HTML Mastery Final Challenge',
  ],
  css: [
    // Basics (1-20)
    'Introduction to CSS',
    'CSS Syntax and Selectors',
    'Colors',
    'Backgrounds',
    'Typography Basics',
    'Font Properties',
    'Text Properties',
    'Box Model',
    'Margin',
    'Padding',
    'Borders',
    'Width and Height',
    'Display Property',
    'Visibility and Opacity',
    'Overflow',
    'Units (px, em, rem, %)',
    'Class and ID Selectors',
    'Combinators',
    'Pseudo-Classes',
    'Pseudo-Elements',
    // Layout (21-45)
    'Positioning (static, relative)',
    'Positioning (absolute, fixed)',
    'Positioning (sticky)',
    'Z-Index',
    'Float and Clear',
    'Flexbox Introduction',
    'Flex Direction and Wrap',
    'Justify Content',
    'Align Items and Content',
    'Flex Grow, Shrink, Basis',
    'Grid Introduction',
    'Grid Template Rows/Columns',
    'Grid Gap',
    'Grid Placement',
    'Grid Areas',
    'Grid Auto Flow',
    'Responsive Design Basics',
    'Media Queries',
    'Mobile-First Design',
    'Viewport Units',
    'Min/Max Width and Height',
    'CSS Variables (Custom Properties)',
    'Calc Function',
    'Aspect Ratio',
    'Container Queries',
    // Styling & Effects (46-70)
    'Box Shadow',
    'Text Shadow',
    'Border Radius',
    'Gradients (Linear)',
    'Gradients (Radial)',
    'Transitions',
    'Transition Timing Functions',
    'Transforms (2D)',
    'Transforms (3D)',
    'Animations (Keyframes)',
    'Animation Properties',
    'Multi-Step Animations',
    'Filters',
    'Blend Modes',
    'Clip Path',
    'Object Fit and Position',
    'Cursor and Pointer Events',
    'Scroll Behavior',
    'Scroll Snap',
    'Custom Scrollbars',
    'Print Styles',
    'Attribute Selectors',
    'Specificity',
    'Cascade and Inheritance',
    'CSS Reset vs Normalize',
    // Advanced (76-100)
    'CSS Architecture (BEM)',
    'CSS Modules',
    'CSS-in-JS Concepts',
    'Logical Properties',
    'Writing Modes',
    'Multi-Column Layout',
    'Shapes',
    'Masking',
    'Counter Styles',
    'Content Property',
    'CSS Functions (clamp, min, max)',
    'Subgrid',
    'CSS Nesting',
    'Color Spaces (hsl, oklch)',
    'Accent Color',
    'Color Scheme',
    'Motion Preferences',
    'Forced Colors',
    'Advanced Selectors (:has, :is)',
    'Cascade Layers (@layer)',
    'View Transitions',
    'Anchor Positioning',
    'Advanced Responsive Patterns',
    'CSS Performance',
    'CSS Mastery Final Challenge',
  ],
  javascript: [
    // Basics (1-20)
    'Introduction to JavaScript',
    'Variables (let, const, var)',
    'Data Types',
    'Operators',
    'String Basics',
    'String Methods',
    'Numbers and Math',
    'Type Conversion',
    'Comparison Operators',
    'If and If-Else',
    'Switch Statement',
    'For Loop',
    'While and Do-While',
    'Break and Continue',
    'Functions',
    'Function Expressions',
    'Arrow Functions',
    'Scope',
    'Hoisting',
    'Template Literals',
    // Core Logic (21-45)
    'Arrays',
    'Array Methods (push, pop, etc)',
    'Array Iteration Methods',
    'Array Destructuring',
    'Objects',
    'Object Methods',
    'Object Destructuring',
    'Spread and Rest Operators',
    'JSON',
    'DOM Introduction',
    'Selecting Elements',
    'Modifying Elements',
    'Creating and Removing Elements',
    'Event Listeners',
    'Event Object',
    'Event Bubbling and Capturing',
    'Form Handling',
    'Local Storage',
    'Session Storage',
    'Error Handling (try/catch)',
    'Regular Expressions',
    'Date and Time',
    'SetTimeout and SetInterval',
    'Math Object',
    'Symbol and Iterators',
    // Intermediate (46-70)
    'Closures',
    'Higher-Order Functions',
    'Callbacks',
    'Promises',
    'Async/Await',
    'Fetch API',
    'Working with APIs',
    'Error Handling in Async',
    'Classes',
    'Inheritance (extends)',
    'Static Methods',
    'Getters and Setters',
    'Private Fields',
    'Modules (import/export)',
    'Default and Named Exports',
    'Map and Set',
    'WeakMap and WeakSet',
    'Generators',
    'Iterables and Iterators',
    'Proxy and Reflect',
    'Optional Chaining',
    'Nullish Coalescing',
    'Tagged Template Literals',
    'Web Workers',
    'Intersection Observer',
    // Advanced (76-100)
    'Event Loop',
    'Microtasks vs Macrotasks',
    'Memory Management',
    'Garbage Collection',
    'Prototypal Inheritance',
    'Object.create and Prototypes',
    'Property Descriptors',
    'Mixins',
    'Design Patterns: Module',
    'Design Patterns: Observer',
    'Design Patterns: Factory',
    'Debounce and Throttle',
    'Currying',
    'Memoization',
    'Functional Programming Concepts',
    'Immutability',
    'Service Workers',
    'IndexedDB',
    'WebSockets',
    'Canvas API',
    'Drag and Drop API',
    'Clipboard API',
    'Performance Optimization',
    'Testing Basics (Jest)',
    'JavaScript Mastery Final Challenge',
  ],
};

// Helper to get topic for a specific language and level
export const getTopic = (language: string, level: number): string => {
  const lang = language.toLowerCase();
  const topics = curriculum[lang];
  if (topics && level >= 1 && level <= topics.length) {
    return topics[level - 1];
  }
  return `Advanced ${language} Concepts`;
};

// Get difficulty tier
export const getDifficulty = (level: number): 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert' => {
  if (level <= 20) return 'Beginner';
  if (level <= 45) return 'Intermediate';
  if (level <= 70) return 'Advanced';
  return 'Expert';
};
